services:
  - type: web
    name: reservas-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "1"
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1 